name: deploy-dev

on:
  push:
    branches:
        - develop

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'sa-east-1'
    TERRAFORM_VERSION: '1.0.9'
    TERRAFORM_WORKING_DIR: './infra'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install dotnet 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: build
      working-directory: ./app/src/LambdaFunction
      run: dotnet build --configuration Release
  
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
       terraform_version: ${{ env.TERRAFORM_VERSION }}
       cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}      
    
    - name: Initialize Terraform
      run: |
       cd ${{ env.TERRAFORM_WORKING_DIR }}
       terraform init
    - name: Deploy Lambda with Terraform
      run: |
       cd ${{ env.TERRAFORM_WORKING_DIR }}
       terraform apply -var-file="ambiente/dev.tfvars" -auto-approve
    
      
      



