name: deploy-dev

on:
  push:
    branches:
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: diretorio do build
      run: cd /home/runner/work/TemplateLambda-net6/TemplateLambda-net6/app/src/LambdaFunction
    
    - name: build
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - run: dotnet build --configuration Release


